#
# This workflow runs on push events and pull_requests of the develop branch
#
# Web app is built and deployed to AWS S3 Bucket.
#
name: Development

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: development
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      #
      # Checkout the repository.
      #
      - uses: actions/checkout@v3
        id: checkout

      #
      # Set node 14
      #
      - uses: actions/setup-node@v3
        with:
          node-version: 14

      #
      # Cache files in ./frontend
      #
      - name: Cache
        uses: actions/cache@v3
        id: use-cache
        with:
          path: |
            node_modules/
            .eslintcache
            .stylelintcache
            **/.cache
            apps/**/node_modules/
            packages/**/node_modules/
            autotests/**/node_modules/
            ~/.cache/Cypress
          key: develop-fe-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            develop-fe-

      #
      # Generate env from secrets
      #
      - name: Generate env
        working-directory: ./apps/web
        run: |
          echo "GRAPHQL_URL=${{ secrets.GRAPHQL_URL }}" > .env
          echo "MOONBASE_EXPLORER=${{ secrets.MOONBASE_EXPLORER }}" >> .env
          echo "SUBSTRATE_EXPLORER=${{ secrets.SUBSTRATE_EXPLORER }}" >> .env

      #
      # Install dependencies and build the app
      #
      - name: Build React App
        id: build-project
        run: yarn install --frozen-lockfile && yarn bootstrap && yarn build

      #
      # Upload the build as artifact
      #
      - name: Artifacts
        id: upload-artifact-build
        uses: actions/upload-artifact@v3
        with:
          name: artifact-fe
          path: |
            apps/web/dist/
            packages/**/dist/

      #
      # Notify on slack if there is a failure
      #
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: ${{ secrets.SLACK_CHANNEL }}
        if: failure()

  test:
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: development
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      #
      # Checkout the repository.
      #
      - uses: actions/checkout@v3
        id: checkout

      #
      # Cache files
      #
      - name: Cache
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            node_modules/
            .eslintcache
            .stylelintcache
            **/.cache
            apps/**/node_modules/
            packages/**/node_modules/
            autotests/**/node_modules/
            ~/.cache/Cypress
          key: develop-fe-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            develop-fe-

      #
      # Run generate scripts
      #
      - name: Generate routes and behaviors
        id: generate-data
        run: yarn prebuild
        working-directory: ./apps/web

      #
      # Run lint
      #
      - name: Lint
        id: lint
        run: NODE=production yarn lint:ci

      #
      # Run tests
      #
      - name: Test
        id: unit-tests
        run: yarn test

      #
      # Download artifact for e2e testing
      #
      - uses: actions/download-artifact@v3
        id: download-artifact
        with:
          name: artifact-fe
          path: autotests/synpress

      #
      # Generate env from secrets for e2e testing
      #
      - name: Generate env
        working-directory: ./autotests/synpress
        run: |
          echo "SECRET_WORDS=${{ secrets.SECRET_WORDS }}" > .env
          echo "METAMASK_VERSION=${{ secrets.METAMASK_VERSION }}" >> .env
          echo "NETWORK_NAME=${{ secrets.NETWORK_NAME }}" >> .env
          echo "RPC_URL=${{ secrets.RPC_URL }}" >> .env
          echo "CHAIN_ID=${{ secrets.CHAIN_ID }}" >> .env
          echo "BLOCK_EXPLORER=${{ secrets.BLOCK_EXPLORER }}" >> .env
          echo "IS_TESTNET=${{ secrets.IS_TESTNET }}" >> .env
          echo "SYMBOL=${{ secrets.SYMBOL }}" >> .env
          echo "WALLET_PASSWORD=${{ secrets.WALLET_PASSWORD }}" >> .env
          echo "ETHERSCAN_KEY=${{ secrets.ETHERSCAN_KEY }}" >> .env

      #
      # Run e2e tests
      #
      - name: E2E test
        id: e2e-tests
        run: ./node_modules/.bin/cypress install && yarn ci:e2e
        working-directory: ./autotests/synpress

      #
      # Upload cypress video to artifact
      #
      - name: Artifacts
        uses: actions/upload-artifact@v3
        id: upload-artifact-cypress
        with:
          name: artifact-fe
          path: |
            autotests/synpress/tests/e2e/videos
            autotests/synpress/tests/e2e/screenshots

      #
      # Notify if there is a failure or if this is a pull_request event
      #
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: ${{ secrets.SLACK_CHANNEL }}
        if: ${{ github.event_name == 'pull_request' || failure() }}

  deploy:
    if: ${{ github.event_name != 'pull_request' }}
    needs: [build, test]
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    environment:
      name: development
      url: http://bloxifi-fe-dev.s3-website.eu-central-1.amazonaws.com/
    steps:
      #
      # Configure AWS credentials
      #
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        id: init-aws
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      #
      # Download the artifact
      #
      - uses: actions/download-artifact@v3
        with:
          name: artifact-fe

      #
      # Upload the app on S3 bucket
      #
      - name: Deploy app build to S3 bucket
        id: deploy
        run: aws s3 sync ./apps/web/dist/ s3://bloxifi-fe-dev --cache-control "max-age=120000" --delete

      #
      # Notify the status of deploy on slack
      #
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: ${{ secrets.SLACK_CHANNEL }}
        if: always()
